// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: LED

#ifndef _LED_UI_H
#define _LED_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Index
void ui_Index_screen_init(void);
extern lv_obj_t * ui_Index;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_front;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_middle;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_back;
extern lv_obj_t * ui_Label3;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_voice_panel;
void ui_event_Panel3(lv_event_t * e);
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_403336390);    // assets/bulb-icon.png
LV_IMG_DECLARE(ui_img_1437063717);    // assets/mic-microphone-icon.png
LV_IMG_DECLARE(ui_img_1804578317);    // assets/mic-microphone-icon-96.png



LV_FONT_DECLARE(ui_font_Kanit24);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
